In [1]:
print("Hello World")


Hello World


In [2]:
import numpy as np

In [3]:

arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [4]:
arr = np.array([[1, 2, 3],[4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [5]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(arr.shape)

(2, 3)


In [6]:
arr = np.array([-10, -5, 0, 5, 10])
print(np.absolute(arr))

[10  5  0  5 10]


In [7]:
arr = np.array([1, 2, 3, 4, 5])
print(np.square(arr))

[ 1  4  9 16 25]


In [8]:
arr=np.array([10,20,30,50])
print(np.sum(arr))

110


In [9]:
arr = np.array([5, 2, 8, 1, 9])
print(np.sort(arr))

[1 2 5 8 9]


In [10]:
print(np.arange(1, 11, 2))

[1 3 5 7 9]


In [11]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(np.transpose(arr))

[[1 4]
 [2 5]
 [3 6]]


In [12]:
import pandas as pd

In [13]:
s = pd.Series([10, 20, 30, 40])
print(s)

0    10
1    20
2    30
3    40
dtype: int64


In [14]:
data = {
    "Name": ["Ram", "Ravi", "Sita"],
    "Age": [20, 21, 22]
}
df = pd.DataFrame(data)
print(df)

   Name  Age
0   Ram   20
1  Ravi   21
2  Sita   22


In [16]:
df.describe()

,Age
count,3.0
mean,21.0
std,1.0
min,20.0
25%,20.5
50%,21.0
75%,21.5
max,22.0


In [17]:
df.describe()

,Age
count,3.0
mean,21.0
std,1.0
min,20.0
25%,20.5
50%,21.0
75%,21.5
max,22.0


In [1]:
import pandas as pd
from sklearn.datasets import load_iris

# Load Iris dataset from sklearn
iris_raw = load_iris()


iris_df = pd.DataFrame(data=iris_raw.data, columns=iris_raw.feature_names)


In [2]:
iris_df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
0,5.1,3.5,1.4,0.2
1,4.9,3.0,1.4,0.2
2,4.7,3.2,1.3,0.2
3,4.6,3.1,1.5,0.2
4,5.0,3.6,1.4,0.2
...,...,...,...,...
145,6.7,3.0,5.2,2.3
146,6.3,2.5,5.0,1.9
147,6.5,3.0,5.2,2.0
148,6.2,3.4,5.4,2.3
